[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/auth/callback"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate" 